### ISSUE TITLE
ประชุมcompro

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#1]
หัวข้อ

**Comment by Kitsunegakawaiinee** [comment]
วันที่ 13/02/23
นัดประชุม 22:00 ผ่านดิส
-กำหนดหน้าที่
-หัวข้อที่จะทำ
-โดยรวมของงาน

**Comment by Kitsunegakawaiinee** [comment]
ข้อสรุปจากการประชุมวันนี้

-ภาพรวม 
	-chat bot
		-สุ่มร้านอาหารให้ได้ (สุ่มได้ในสโคปใกล้ๆมอ)
			
-สิ่งที่บอทถาม 
				-กินประเภทไหน
				-กินแถวไหน
				-กินตอนไหน
				-เอาผักไหม
				-และอื่นๆ
		
		-ถามตารางเรียนได้ (ถ้าทันเวลา)
		-อาจมีเพิ่มอย่างอื่นได้ถ้ามีเวลา
