### ISSUE TITLE
ฝั่งประตูวิศวะ

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#10]

**Comment by YotsawatSuki** [comment]
<ร้านอาหาร> <เมนู>

ข้าวผัดปูเยาวราช
- กะเพราหมูกรอบ
- ก๋วยเตี๋ยวไก่ตุ๋นมะระ
- พริกแกงทะเล
- ปลาหมึกผัดไข่เค็ม
- สุกี้น้ำหมู

ข้าวต้มบุษบา
- ยำไข่เค็ม
- คะน้าน้ำมันหอย
- แกงจืดเต้าหู้หมูสับ
- พะโล้ไข่
- ไข่เค็มผัดหมูสับ

ก๋วยจั๊บญวน_หลังมอ
- ก๋วยจั๊บญวน
- เล้งแซ่บ
- ญวนต้มยำ

สเต๊กลุงเม่น
- เบอร์เกอร์
- สเต็ก
- ข้าวหมูเทอริยากิ
- ข้าวหน้าหมู
- ข้าวหมูผัดกิมจิ

ราชาหมูทอด_เล้งแซ่บ
- ข้าวหมูทอดกระเทียม
- ข้าวหมูทอดคลุกฝุ่น
- ซุปเปอร์เล้งพริกสด
- ข้าวหมูทอดพริกแห้ง

อาหารตามสั่ง_ByLachada
- ข้าวผัดกระเทียมหมูย่าง
- กระเพราเอ็นโคขุนเปื่อย
- ไก่ทอด_รชต
- ข้าวผัดมั่วเส้นหมูย่าง

ก๋วยเตี๋ยวเป็ดแม่บุญรอด
- ข้าวกะเพราเป็ด
- ก๋วยเตี๋ยวเป็ด
- ต้มแซ่บเนื้อ
- ข้าวหน้าเป็ด

ข้าวมันไก่_ต่อประตูเกษตร
- ข้าวมันไก่
- ก๋วยเตี๋ยวหมูต้มยำมะนาว
- เย็นตาโฟต้มยำ
- ก๋วยเตี๋ยวต้มยำไก่
