### ISSUE TITLE
แก้code mineass.cpp

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#17]
![image](https://user-images.githubusercontent.com/110962980/223668424-34d00fd6-79ec-4cd5-b820-6b354caf5378.png)

-บรรทัด 13 เปลี่ยนเป็นswitch caseเพราะเราต้องการให้ผู้เลือกร้านเป็นตัวเลข
-แก้โค้ดตรงบรรทัดที่ 14 เพราะมันรันในเครื่องอื่นไม่ได้เพราะfixตำแหน่งไว้
-เพิ่มลูปเข้าไปด้วยเช่นคอนใส่เลขผิดก็จะถามใหม่
-เพิ่ม clear buffer เมื่อผู้ใช้ใส่ไปหลายๆค่า

**Comment by Kitsunegakawaiinee** [comment]
เราคิดว่าในบรรทัดที่ 14 อ่ะ มันใส่แค่ `string fileName = "Menu_in_store/"+storename+"txt` ก็น่าจะพอแล้วนะเพราะ มันอยู่ folder เดียวกันอยู่แล้ว มันหากันเจออยู่แล้ว

และถ้าบอกละเอียดขนาดนั้นอ่ะ ถ้ามีคนที่เก็นไว้คนละไดรฟ์อ่ะ มันจะหาไม่เจอนะ เพราะว่ามันจะหาที่ User ใน ไดรฟ์ C อย่างเดียวเลย
