### ISSUE TITLE
mineass.cpp location AAA

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#18]
![image](https://user-images.githubusercontent.com/110962980/223670707-ea61e9b9-56b7-4637-a72a-edc926dd7d9d.png)

**Comment by Kitsunegakawaiinee** [comment]
Location : AAA คือไรอ่ะ

**Comment by AdisornSjr** [comment]
เขียนเผื่อไว้เฉยๆ แบบเผื่อ location มีหลายบรรทัด
