### ISSUE TITLE
ช่วยดูโค้ดด้วยครับ

### ISSUE THREAD

**Issue by YotsawatSuki** [BUFFVODAKA/include-pa-sah-thai#21]
```
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cstdlib> 
#include <ctime>

using namespace std;

ifstream RF1,RF2;

    class Store
    {
        vector <string> menu;
        string store_name,where;
        string text;
        bool set_where = false, noname = true;
        public:
        Store(string);
        void show_data(); 
        bool check_menu(string input);
        int acess_menu_size(); 
        string assecc_menu(int index); 
        string show_name();
        string show_where();
        void show_menu();
        void name_and_location();

    };


Store::Store(string storename)
{
    store_name = storename;
    string filename = "data_store_menu//menu//" + storename +".txt";
    RF2.open(filename);
    while(getline(RF2, text))
    {
        
        if(text == "where")
        {
            set_where = true;
            continue;
        }

        if(set_where)
        {
            where = text;
            set_where = false;
            continue;
        }

        if(text == "/where") continue;

        menu.push_back(text);

    }
    RF2.close();
}

void Random_Store(){
    vector<Store> allstore;
    string filename = "data_store_menu/store_list.txt";
    RF1.open(filename);

    if (!RF1.is_open()) { 
        cout << "Failed to open file!" << endl;
        exit(1);
    }

    string name;
    while(getline(RF1,name))
    {
        Store name(name);
        allstore.push_back(name);
    }
    
}

int main() 
{
    Random_Store();
}
```

**Comment by YotsawatSuki** [comment]
อยากให้ช่วยดูหน่อยว่ามันได้ไหมวิธีนี้น่ะ
```
void Random_Store(){
    vector<Store> allstore;
    string filename = "data_store_menu/store_list.txt";
    RF1.open(filename);

    if (!RF1.is_open()) { 
        cout << "Failed to open file!" << endl;
        exit(1);
    }

    string name;
    while(getline(RF1,name))
    {
        Store name(name);
        allstore.push_back(name);
    }
```
 คือเราอยากสร้างเวกเตอร์ของ class มาเก็บตัวที่เราทำการ constructor เพื่อให้มันอัปเดตเมมเบอร์

**Comment by Kitsunegakawaiinee** [comment]
เท่าที่ดูนี่คือเราเข้าใจว่าที่เขียนมาน่าจะเป็นการส่งชื่อร้านเข้าไปเพื่อสร้าง object แล้วเก็บใน vector

เราคิดว่าลองเปลี่ยนเป็นแบบนี้ไหม

`void Random_Store()
{
    vector<Store> allstore;
    string filename = "data_store_menu/store_list.txt";
    RF1.open(filename);

    if (!RF1.is_open()) 
    { 
        cout << "Failed to open file!" << endl;
        exit(1);
    }
    else
    {
        string name;

        while(getline(RF1,name))
        {
            Store name(name);
            allstore.push_back(name);
        }
    }
}`

คือเปลี่ยนมาเป็นดึงไฟล์จาก txt เมื่อสามารถเปิดไฟล์ได้หรือ (!RF.is_open()) เป็นเท็จ



จากที่ดูอันนี้อ่ะ
`void Random_Store(){
    vector<Store> allstore;
    string filename = "data_store_menu/store_list.txt";
    RF1.open(filename);

    if (!RF1.is_open()) { 
        cout << "Failed to open file!" << endl;
        exit(1);
    }

    string name;
    while(getline(RF1,name))
    {
        Store name(name);
        allstore.push_back(name);
    }
    
}`
คือมันน่าจะดึงไฟล์แม้ว่าจะเปิดไฟล์ไม่ได้ เลยไม่แน่ใจว่ามันจะบัคไหม

**Comment by Kitsunegakawaiinee** [comment]
ลอกเปลี่ยนชื่อ object เป็นชื่ออื่นได้ปะ

`void Random_Store(){
    vector<Store> allstore;
    string filename = "data_store_menu/store_list.txt";
    RF1.open(filename);

    if (!RF1.is_open()) { 
        cout << "Failed to open file!" << endl;
        exit(1);
    }

    string name;
    while(getline(RF1,name))
    {
        Store (เปลี่ยนชื่อตรงนี้เป็นอย่างอื่นที่ไม่ใช่ name)(name);
        allstore.push_back(name);
    }
}`

**Comment by YotsawatSuki** [comment]
ตอนนี้ได้แหละ รันแล้วไม่ขึ้น error ตรง terminal แหละ ขอบคุณครับบ
