### ISSUE TITLE
ใส่ตัวอักษรแล้วแตกRandom_Drink.h 

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#22]
บรรทัดที่31
![image](https://user-images.githubusercontent.com/110962980/225283925-9e5916a8-9c65-420c-a3f4-459c9e2f8319.png)

**Comment by BUFFVODAKA** [comment]
น่าจะแก้ int choice เป็น char choice

**Comment by Kitsunegakawaiinee** [comment]
เราแก้ให้ละ 

คือเปลี่ยนจากรับ choice ที่เป็น int ให้เป็น string
