### ISSUE TITLE
ข้อมูลในมอเร่งด่วน!!!!

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#25]
ใครก้ได้หาข้อมูลในมอหน่อย
เราจะตุยละ

**Comment by AdisornSjr** [comment]
![image](https://user-images.githubusercontent.com/110969563/225651157-42fc99ac-23dc-4a1f-bd92-76994f5bb1b5.png)
ผ่านหลังมอตอนเย็นได้เพิ่มมา
