### ISSUE TITLE
ประชุมจะทำcodeรูปแบบอะไร

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#5]
-file I/O
-array
-class

**Comment by Kitsunegakawaiinee** [comment]
#สรุปการประชุม 28/02/2566 เรื่อง รูปแบบของโค้ดคร่าวๆ

![image](https://user-images.githubusercontent.com/99963600/221799314-44be7e17-8dd6-4f37-ba16-3ad0781ff715.png)
