### ISSUE TITLE
ร้านระหว่างประตูศึกษาถึง S1

### ISSUE THREAD

**Issue by BUFFVODAKA** [BUFFVODAKA/include-pa-sah-thai#9]
-ตำแหน่ง
-ชื่อร้าน
-menu

**Comment by YotsawatSuki** [comment]
ตำแหน่ง : ทางเข้าซอยวัดอุโมงค์
ชื่อร้าน : กะเพราเนื้อเนื้อ
เมนู : {
1). กะเพราไก่สับ
2). กะเพราหมูสับ
3). กะเพราเนื้อสับ
4). กะเพราเนื้อติดมัน
}

**Comment by YotsawatSuki** [comment]
ตำแหน่ง : ทางเข้าซอยวัดอุโมงค์
ชื่อร้าน : The Steak
เมนู : {
1). เสต็ก = {วัว,หมู,ปลา,ไก้}
2). เบอร์เกอร์ = {บาบิคิวหมู,ไก่ทอด,ชีสเบอร์เกอร์}
3). สลัด = {ผักเขียว, ทูน่า, เบคอน, เนื้อหมู วัว ปลา ไก่ย่าง}
4). ของทานเล่น = {เฟรนฟราย ,นักเก็ต ,ชีสบอล ,ออนเนียนริง ,ไก่ป็อบ}
}
